### ISSUE TITLE
Link broken in "Get started with querying a Kusto database in Microsoft Fabric" scenario lab

### ISSUE THREAD

**Issue by k-krupka** [MicrosoftLearning/mslearn-fabric#108]
hi team,
small one
https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/12-query-data-in-kql-database.html#create-a-kql-database
in "Create a KQL Database" section, in point number 4, there is a link broken (bottom of this screenshot):

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/20299573/8e8f6d07-2edf-4b4e-ab80-2a43ed918526)

**Comment by k-krupka** [comment]
Just realized, that once you load the new KQL database, it's name is "Automotive" and later in the lab, the table name "Trips" is used. 

Maybe we can align in one go. See:
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/20299573/c86ff17c-61ff-4cd0-be07-0ac571835c70)

**Comment by TheJamesHerring** [comment]
Thanks for bringing this up. I will be updating tomorrow. 
James H

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring - nudge!

**Comment by TheJamesHerring** [comment]
Apologies, this was fixed but I failed to close. It had an uppercase in the name where it should have been lower. gotta get out of the camelcase world.

**Comment by TheJamesHerring** [comment]
closing
