### ISSUE TITLE
15 Work with model relationships

### ISSUE THREAD

**Issue by nugysemail** [MicrosoftLearning/mslearn-fabric#114]
# Module: 15 Work with model relationships
#### Step: 07

Description of issue : 
When choosing Close & Apply in Power Query, this error messages pop up in
2 Tables : Sales & Sales Order : "The key didn't macth any rows in the table".

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/2998731/84b78aec-1325-4298-b2cb-21c6e2cb438e)

Investigating it deeper, I found that the 2 queries (Sales and Sales Order) refer to vFactSales.
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/2998731/b25cab74-b005-40c7-8cc6-5b60c6e0dd8f)

I have downloaded the AdventureWorksDW2022 database but didnt find any vFactSales View or Table. Please provide the backup the Database.

**Comment by GraemeMalcolm** [comment]
Any progress on resolving this?

**Comment by AngieRudduck** [comment]
Sorry for the delayed response here, but we have triaged and identified the issue. There is a view that isn't in the default AdventureWorksDW2022 database. We plan to update the database backup files in the Allfiles/00-Setup/DatabaseBackup file on June 14 to resolve this issue.
