### ISSUE TITLE
Need more guidance on which fields to use when creating relationships between tables

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/mslearn-fabric#117]
14-create-a-star-schema-model
Step: Create relationships between tables

It is not mentioned which fields should be selected for creating the relationships

"Create relationships to the Trip fact table from the Geography and Weather dimensions, repeating the step above. Also ensure these relationships are One to many, with one occurance of the key in the dimension table, and many in the fact table."

For Geography table: is it DropoffGeographyId or PickupGeographyId?
From Weather table: is it DateID?

**Comment by weslbo** [comment]
also need more guidance on One to Many.... (as in the picture it is opposite between trip and weather table)

**Comment by AngieRudduck** [comment]
Resolved. https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/14-create-a-star-schema-model.html#create-relationships-between-tables
