### ISSUE TITLE
Code issues in the lab 08d-data-science-batch

### ISSUE THREAD

**Issue by usamabinrauf** [MicrosoftLearning/mslearn-fabric#118]
#### Description of issues:
`table_name` is not initialized in the code snippet which causes error on running the code cell. Moreover, `df` is passed as a parameter in the line of code `df_test = model.transform(df)` instead of `df_test`.

#### Solution:
1. Initialize `table_name` using `table_name = "diabetes_test"` and add it before the line of code `df_test = spark.read.format("delta").load(f"Tables/{table_name}")`.
1. Replace `df_test = model.transform(df)` with `df_test = model.transform(df_test)`.

**Comment by afelix-95** [comment]
1. As long as you ran the previous code snippet first and created the delta table, the variable `table_name` can still be used in the next code snippet without being declared again.
2. `df` in `df_test = model.transform(df)` is actually referring to the type of input (DataFrame) applied to the `transform` method of the `MLFlowTransformer` and not to the object `df_test` directly.

So, running the code snippets as they are in the exercise should produce the desired output without errors.
