### ISSUE TITLE
Additional Spaces

### ISSUE THREAD

**Issue by thomasthaddeus** [MicrosoftLearning/mslearn-fabric#123]
# Module: Analyze data with Apache Spark
#### Step: 09

Description of issue

The code class is the wrong code class as all the rest of the python blocks use `language-Python` not language-python

Repro steps:

1. this is how it shows up in the html which is not how it is written in the markdown

```html
    <pre><code class="language-python"> from pyspark.sql.types import *

 orderSchema = StructType([
    StructField("SalesOrderNumber", StringType()),
    StructField("SalesOrderLineNumber", IntegerType()),
    StructField("OrderDate", DateType()),
    StructField("CustomerName", StringType()),
    StructField("Email", StringType()),
    StructField("Item", StringType()),
    StructField("Quantity", IntegerType()),
    StructField("UnitPrice", FloatType()),
    StructField("Tax", FloatType())
    ])

 df = spark.read.format("csv").schema(orderSchema).load("Files/orders/*.csv")
 display(df)
</code></pre>
```

1.
1.

**Comment by thomasthaddeus** [comment]
Must have deleted the part about how because it is the wrong class, it seems to be adding an extra space to the front of all the text in the block

**Comment by afelix-95** [comment]
Hi @thomasthaddeus perhaps you were interacting with the .md file in Code mode instead of Preview? Those extra spaces are for fixing an issue with leading spaces in Preview mode or HTML and should not be a problem when you copy the code block from those. 
Also, enabling syntax highlighting can be done with either `Python` or `python` without any differences in the output. 
So, for best learning experience I'd recommend doing the lab through its HTML version at https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/02-analyze-spark.html

**Comment by thomasthaddeus** [comment]
@afelix-95 its still an issue both of these are the same as they were before. I'm looking at the html, the first one is the block i mentioned, the second one is a different block that doesnt have leading spaces.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/92204097/4273f15c-b32b-455c-84be-a6b554cd3c6e)

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/92204097/8e1f74bb-2642-4a82-b626-26d5abd55b28)

Heres the code in the sources for both of the previous snapshots.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/92204097/5701390c-b650-45a1-943b-ea2202c7b85b)

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/92204097/c482d207-ed18-427b-8ed1-c8aa47d0d16a)

**Comment by afelix-95** [comment]
@thomasthaddeus Thank you for the screenshots and further clarification. Looking again at the code, there was indeed an indentation mistake in the code block of your first screenshot that is omitted in Preview mode but not in the HTML page. It is fixed now.
