### ISSUE TITLE
Relationship schema incorrect in diagram

### ISSUE THREAD

**Issue by davecatt** [MicrosoftLearning/mslearn-fabric#135]
# Module: 
#### Step: 6

Description of issue
The instructions to create relationships state "Create relationships to the Trip fact table from the Geography and Weather dimensions, repeating the step above. Also ensure these relationships are One to many, with one occurance of the key in the dimension table, and many in the fact table."

But the diagram underneath shows the relationship between Trip and Weather to be Many:1

Repro steps:

1.
1.
1.

**Comment by AngieRudduck** [comment]
Under review

**Comment by AngieRudduck** [comment]
Resolved
