### ISSUE TITLE
Inaccurate/outdated information about Calculation Groups in 16-use-tools-to-optimize-power-bi-performance.md

### ISSUE THREAD

**Issue by JamesDBartlett3** [MicrosoftLearning/mslearn-fabric#136]
[Power BI Desktop gained native support for creating calculation groups in October 2023](https://learn.microsoft.com/en-us/power-bi/transform-model/calculation-groups) with the introduction of the [Model explorer view](https://learn.microsoft.com/en-us/power-bi/transform-model/model-explorer), so [this section of 16-use-tools-to-optimize-power-bi-performance.md](https://github.com/MicrosoftLearning/mslearn-fabric/blob/17481a21195a728994b9afcee40f803ca953502e/Instructions/Labs/16-use-tools-to-optimize-power-bi-performance.md?plain=1#L32) is now inaccurate/outdated.

**Comment by AngieRudduck** [comment]
You're accurate that calculation groups can now be done natively in the product. The tool identified still also supports the task.
