### ISSUE TITLE
UI Change for Data Wrangler, lab instruction is outdated

### ISSUE THREAD

**Issue by adamlimsft** [MicrosoftLearning/mslearn-fabric#149]
# Module: Get started with data science in Microsoft Fabric
#### Step: 04. 'Navigate to the Operations panel, expand Formulas, and then select Create column from formula.'

Description of issue
UI has changed in Data Wrangler, there is no 'Create column from formula' option anymore. 

Repro steps:
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/24862662/13924275-e63a-472d-9703-3ebde9f61ec6)

**Comment by adamlimsft** [comment]
@AngieRudduck  Hi Angie could you help assign this to Mary-Jo? Don't think I have the privilege to assign.

**Comment by afelix-95** [comment]
Hi @adamlimsft. Now we can use Data Wrangler with both Spark and Pandas dataframes, but the options available for each of them are slightly different. In this case, the **Create column from formula** option is only available for Pandas dataframes, so if you're opening the Data Wrangler with a Spark dataframe, that option won't appear.
