### ISSUE TITLE
Additional trailing spaces in code block - https://raw.githubusercontent.com/MicrosoftLearning/mslearn-fabric/main/Instructions/Labs/06d-secure-data-warehouse.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/mslearn-fabric#155]
# Module: 'Secure a Microsoft Fabric data warehouse'
#### Step: 05

Description of issue

There are 3 additional trailing spaces after the opening tsql code block, and depending on ALH/parser used for markdown rendering this can lead to display issues.  Can these 3 spaces be deleted?

![image](https://github.com/user-attachments/assets/3da7c314-9f2f-4c80-b264-632ca1a550e6)

**Comment by theresa-i** [comment]
Yes they can be deleted.  Thanks!
