### ISSUE TITLE
Yellow-tax-opt reference in Lab

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/mslearn-fabric#156]
Lab: Ingest data with Spark and Microsoft Fabric notebooks
Section: Analyze Delta table data with SQL queries
Step: 2

Script references yellow-tax-opt table which does not exist. In
Section: Transform and load data to a Delta table
Step: 1

there is a comment to # Replace with your desired table name. Perhaps the table name should either be hard-coded, or the comment should be added to the code section above.

**Comment by afelix-95** [comment]
Thanks for pointing it out! The code snippet in step 2 was part of a former task related to write optimization features in Fabric. Since these features are now enabled by default, the comparison task is not relevant anymore and therefore this step should be removed. 

> You can read more about the optimization features here: https://learn.microsoft.com/en-us/fabric/data-engineering/delta-optimization-and-v-order?tabs=sparksql
