### ISSUE TITLE
Error in Lab: Get started with Eventstream in Real-Time Intelligence

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/mslearn-fabric#159]
Lab/Demo: Get started with Eventstream in Real-Time Intelligence
#### Step: 1C

Step asks learner to "Fill out the properties of the Group by settings section", but no property information is provided.
The next step (2) starts with "Once you create the Group By transform event".

It appears that a properties table for step 1C is missing

**Comment by afelix-95** [comment]
Thanks for pointing that out! We updated the lab instructions to make things more clear.
