### ISSUE TITLE
Image has wrong relationship

### ISSUE THREAD

**Issue by christabelle** [MicrosoftLearning/mslearn-fabric#161]
# Lab: 14-Create and explore a semantic model
#### Step: 5. Drag the tables into position so that the Trip fact table is located at the bottom of the diagram, and the remaining tables, which are dimension tables, are located around the fact table.

Description of issue
The image provided show the relationship to be 1:* between Trip and Date, where it has to be *:1 like the other relationships.

![image](https://github.com/user-attachments/assets/1fed3c43-9484-42ed-ac9d-f468cb78143a)

**Comment by afelix-95** [comment]
Thank you for pointing that out! Image corrected.
