### ISSUE TITLE
Lab #1: Updated UI behavior for report builder

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/mslearn-fabric#171]
Regarding the following step:

![image](https://github.com/user-attachments/assets/a0ca5082-5609-432c-a868-3a9dcc66da65)

Fabric now opens reports in the same window. Thus instead of closing a new window we should direct users to navigate back to the SQL endpoint.

Please update instructions accordingly.

**Comment by afelix-95** [comment]
Thanks for pointing it out. Fixed now.
