### ISSUE TITLE
"Save as KQL queryset" isn't displayed, modify title via dropdown instead

### ISSUE THREAD

**Issue by ConcreteGannet** [MicrosoftLearning/mslearn-fabric#192]
# Module: 07
#### Step: 9

https://github.com/MicrosoftLearning/mslearn-fabric/blob/main/Instructions/Labs/07-real-time-Intelligence.md

"Save as KQL queryset" isn't displayed. The user interface has been changed. At top left is the name of the queryset with a dropdown arrow beside it. Click on the name to edit and and set a name. I'll put together a pull request for this.

This lab is also used in DP-603.

**Comment by afelix-95** [comment]
The name at the top left of the portal is actually the database name. Now the KQL queryset is automatically saved and we can't actually rename it. The step mentioned was removed from the instructions to avoid confusion.
