### ISSUE TITLE
clarify code

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/mslearn-fabric#200]
In this exercise:
https://github.com/MicrosoftLearning/mslearn-fabric/blob/main/Instructions/Labs/03b-medallion-lakehouse.md
under : Transform data for gold layer
step: 6

why didnt we add update keyword in the highlighted step?
   ) \
 .whenNotMatchedInsert(values =
    {
      "OrderDate": "updates.OrderDate",
      "Day": "updates.Day",
      "Month": "updates.Month",
      "Year": "updates.Year",
      "mmmyyyy": "updates.mmmyyyy",
 >>>>>>
![Screenshot 2024-11-13 175955](https://github.com/user-attachments/assets/b8701c8e-dd62-48b3-b38e-0b6d22484722)
     "yyyymm": "yyyymm"

If it is not a typo please clarifty and explain what is done here

**Comment by theresa-i** [comment]
@MTawfik86 Thanks. This will be updated next week.

**Comment by theresa-i** [comment]
@MTawfik86 This has been fixed.

**Comment by MTawfik86** [comment]
Great work thank you very much
