### ISSUE TITLE
Error Spark_User_WASB_NoCredentials

### ISSUE THREAD

**Issue by evening-apartment** [MicrosoftLearning/mslearn-fabric#205]
# Module: Ingest data with Spark and Microsoft Fabric notebooks
#### Step: 3

Description of issue

https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/10-ingest-notebooks.html

Getting an error when trying to run a cell with the code provided by exercise.

<img width="860" alt="image" src="https://github.com/user-attachments/assets/e12a22ab-f333-4adc-928c-c29da1d3309d">

Repro steps:

1. Copy code
2. Paste in the code cell
3. Run cell

**Comment by afelix-95** [comment]
This lab was tested today with multiple accounts and in both VM and local environments. In all cases the connection was established and the data properly read. Most likely it was a temporary issue with the credential/connection configuration of the runtime session you were using. Closing the issue as no repro but feel free to open it again if the problem persists.
