### ISSUE TITLE
Lab 6 - Azure Open Dataset is no longer accepting anonymous read requests #193

### ISSUE THREAD

**Issue by ForTheLoveOfLearning** [MicrosoftLearning/mslearn-fabric#207]
Hi there, it appears learners are facing this same issue in my training session today. Is there a workaround for this?

_Originally posted by @ForTheLoveOfLearning in https://github.com/MicrosoftLearning/mslearn-fabric/issues/193#issuecomment-2486696484_

**Comment by afelix-95** [comment]
We received a few reports of this issue last Tuesday. The lab was tested today with multiple accounts and in both VM and local environments. In all cases the connection was established and the data properly read. Most likely it was a temporary stability issue with the runtime sessions that resulted in faulty configuration of the credentials/connection setup. Closing the issue as no repro, but feel free to open it again if the problem persists.
