### ISSUE TITLE
Unable to "Load to Tables" in Fabric tutorial using the provided sales.csv file

### ISSUE THREAD

**Issue by alwaysLernin** [MicrosoftLearning/mslearn-fabric#22]
# Module: mslearn-fabric
#### Step: 03

Description of issue
Update: This can be disregarded. After doing some data cleanup on the data provided in the tutorial, I was able to load to table. The link in the tutorial opened raw data in the browser window which, when put into excel created a bad .csv due to the comma's used in the Item field. I would recommend that the tutorial provide a download link to a clean .csv file.

Working through the MSLearn-fabric tutorial on the "Load file date into a table" step on this page (https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/01-lakehouse.html) I get a 400 error. It is possible that this is due to my changing some of the default tenant permissions on initial setup. I couldn't find a way to reset those to the default permissions. If that is a possible cause, then can anyone point me to a way to reset the permissions or a list of the defaults? If not, then I really don't know where to start. Thanks for any help.

Repro steps:

1. Multiple attempts over a couple of hours.
1.
1.

**Comment by linusyoung** [comment]
I got the same error message as I try to create any delta tables. 

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/1628500/0d566313-15a7-43e3-aa37-050d0abb27f4)

**Comment by Mihai-Ac** [comment]
Hello @alwaysLernin and @linusyoung 

I have tried several times, but I couldn´t reproduce any of these errors.
Have you tried running the content within a new workspace?

Regards,
Mihai

**Comment by GraemeMalcolm** [comment]
It could be related to the permission changes, or it could just be an issue with the workspace as Mihai suggests - with early preview services like this it can be difficult to tell. We can't repro the issue in a clean setup, so closing this as it doesn't appear to be an issue with the content per-se. If you figure out a resolution @alwaysLernin, let us know!

**Comment by linusyoung** [comment]
> Hello @alwaysLernin and @linusyoung
> 
> I have tried several times, but I couldn´t reproduce any of these errors. Have you tried running the content within a new workspace?
> 
> Regards, Mihai

@Mihai-Ac,

yes, I tried creating new workspaces multiple times. not sure where I can check these permissions.

**Comment by gmorgan28** [comment]
I also get the same errors. Have tried in multiple workspaces:

org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Create database for GMLakehouse002 is not permitted using Apache Spark in Microsoft Fabric. ).

**Comment by moeeljawadoph** [comment]
Having the same problem with the files found in the Book Recommendations fabric sample, when checking the Use Header for column names:
<img width="289" alt="image" src="https://github.com/MicrosoftLearning/mslearn-fabric/assets/112408177/8f9a9efe-a51a-4b6d-b5ca-e7dc1b5c4ccf">
When unchecking that option, the file is loaded correctly as a table, but strangely the first row in the CSV file appears at row 11 of the table :
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/112408177/4e9faf02-beff-4dc4-a5f6-7041459ede34)
