### ISSUE TITLE
Lab8 and pandas loading generated code

### ISSUE THREAD

**Issue by mycaule** [MicrosoftLearning/mslearn-fabric#24]
#### Repro steps:

1. Copy the `churn.csv` to a subfolder named `data/`
2. load the `churn.csv` file with pandas with a Notebook from [this step](https://github.com/MicrosoftLearning/mslearn-fabric/blob/main/Instructions/Labs/08-data-science.md#load-data-into-a-dataframe)
3. `FileNotFoundError`

```python
import pandas as pd
# Load data into pandas DataFrame from "/lakehouse/default/" + "Files/churn.csv"
df = pd.read_csv("/lakehouse/default/" + "Files/churn.csv")
display(df)
```

Generated code missed the subfolder `data/`

**Comment by Mihai-Ac** [comment]
Hello @mycaule 

The [instructions ](https://github.com/MicrosoftLearning/mslearn-fabric/blob/main/Instructions/Labs/08-data-science.md#create-a-lakehouse-and-upload-files) do not mention any **data** folder for the churn.csv file. The file should be uploaded in the **Files** node. 
In the case that a student created a folder and uploaded the churn.csv file in there, the student can : Navigate to the file, select the ellipsis **...** , from there select **Load data** and then select **Pandas**. This will create a new cell in the notebook with the required code to load the content of that file.

Best regards,
Mihai
