### ISSUE TITLE
Leading spaces in code blocks

### ISSUE THREAD

**Issue by pseudoniem** [MicrosoftLearning/mslearn-fabric#26]
# Module: Any
for instance https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/04-ingest-pipeline.html#create-a-notebook

#### Description of issue
Each line of the code blocks starts with a leading space. When you copy this and paste it into a notebook, the notebooks complains (not errors, but annoying warnings) and so do I. (See screenshot at the bottom).
You know what kind of people are working with this; you can't put them through this kind of eye sore. 
I kindly ask you to remove these spaces at the beginning of the lines, to reduce overall stress levels. 

Screenshot of the spaces:
![tempsnip](https://github.com/MicrosoftLearning/mslearn-fabric/assets/28535202/e468875f-52d6-4c08-bf61-72ec435a95f6)

The warning in the notebook:
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/28535202/5c94a792-a5ac-4a43-a55b-39f0ef8879db)

**Comment by ShettyGaneshprasad** [comment]
In code base there is no space,
but when seen from learning site we have a leading space.

**Comment by AngieRudduck** [comment]
@ShettyGaneshprasad , when you say it's on the learning site, can you provide the exact link you found a leading space?

**Comment by GraemeMalcolm** [comment]
Also, are you using the Copy Code button in the exercise page UI, or literally selecting and copying the code block?

**Comment by ShettyGaneshprasad** [comment]
@AngieRudduck , here's the link: https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/02-analyze-spark.html

**Comment by ShettyGaneshprasad** [comment]
@GraemeMalcolm Even after using copy button I am getting space before every line. 

For example:

 df = spark.read.format("csv").option("header","false").load("Files/orders/2019.csv")
 # df now is a Spark DataFrame containing CSV data from "Files/orders/2019.csv".
 display(df)

**Comment by GraemeMalcolm** [comment]
Hmm. This seems to be an issue with how GitHub pages is rendering the code markdown blocks. The extra space isn't in the source, but seems to get added to the code block when the markdown is rendered to HTML.
We'll investigate and try to determine if we can do anything to address it.

**Comment by GraemeMalcolm** [comment]
Update - this may be related to the line terminator in the source markdown - continuing to investigate...

**Comment by GraemeMalcolm** [comment]
We've raised a ticket with GitHub, as this seems to affect all GitHub pages. The Markdown spec requirements for indented code blocks is to use a 4-space tab to indent the code "fence" and the actual code it contains, like this:
1. List item
2. List Item

    ```python
    def some_code:
    ```

3. List item

**Comment by GraemeMalcolm** [comment]
I've implemented a workaround for the time being. Leaving the issue open until we get a real resolution.
