### ISSUE TITLE
Fabric Tutorial loading sales csv file doesn't work

### ISSUE THREAD

**Issue by gmorgan28** [MicrosoftLearning/mslearn-fabric#27]
Following this tutorial there are a number of issues loading the  sales csv file from the lake to table
Tutorial: https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/01-lakehouse.html

Keep getting the following error when trying to load the file to table:

org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Create database for GMLakehouse002 is not permitted using Apache Spark in Microsoft Fabric. )

Have tried creating new Fabric Workspace, editing the csv before import, smaller files etc.
The file loads ok into the Lake but every time load to Tables fails with the error above.

**Comment by gmorgan28** [comment]
I have enabled Fabric Preview for our organisation in the Admin portal and still no luck.
Are others facing similar issues?

**Comment by gmorgan28** [comment]
I'm now getting a different error:
Unable to submit this request because all the available capacity is currently being used. Cancel a currently running Notebook or Spark Job Definition job, increase your available capacity, or try again later.

Not sure why I'm getting this. Perhaps it has something to do with Preview... anyway will try again later to see what happens

**Comment by GraemeMalcolm** [comment]
This seems to be a capacity issue related to the preview itself rather than an error in the exercise content.
Unfortunately, we can't provide support for the service here - only the content.
I suggest waiting, and trying with a new workspace.
