### ISSUE TITLE
Real-Time Analytics exercise: error message using abfss to create KQL db

### ISSUE THREAD

**Issue by TarekArthurAzim** [MicrosoftLearning/mslearn-fabric#28]
# Module: Get started with Real-Time Analytics in Microsoft Fabric
#### Step: Paste the ABFS path to your sales.csv file, which you copied to the clipboard previously

*** This seem related to (but distinct from) a previous issue: Lab 7 Error importing from OneLake #18 ***

Description of issue
Using the abfss:// path did not work; it generated an error about being in the wrong format.  I used the https:// path instead, which worked.

I also created a new "sales" sub-folder under Files in the Lakehouse for this exercise; I don't know if that was strictly speaking necessary, but it seemed consistent with prior exercises.

Repro steps:
1. Real-time Analytics
2. Home page
3. select KQL database
4. Get data
5. OneLake
6. Source in wizard - generates error about file path format when using abfss:// string copied from sales.csv property

**Comment by GraemeMalcolm** [comment]
So, we originally used the https URL but that started failing, so we switched to the abfss URL. Seems that's now failing - this may be related to the default protocol used for OneLake files, or some sort of regional issue when connecting to OneLake. Either way, it's a distraction from the main point of the lab; which is to use KQL to query a table. The most practical thing to do here is probably to update the lab to just import the CSV file directly into the KQL table by uploading it, and skip the creation of the Lake house altogether.

**Comment by TarekArthurAzim** [comment]
Thanks! (OK if I leave it to you all to close at your discretion?)

**Comment by TheJamesHerring** [comment]
I'll take a look at skipping the Lake House portion in the lab ASAP. JH

**Comment by TheJamesHerring** [comment]
Updated the lab to focus on the KQL - Removed Lakehouse portion.
