### ISSUE TITLE
Organize Fabric Lakehouse - Lab - Step 14 Error

### ISSUE THREAD

**Issue by willrod369** [MicrosoftLearning/mslearn-fabric#42]
# Module: Organize a Fabric lakehouse using medallion architecture design
#### Step: 14

Description of issue
*Error when running script from training (see attached image). Solution was to unindent lines 5 through 24*

Repro steps:

1. Work until Step 14
2. Run Step 14
3. See Error
4. solution: Unindent lines 5 though 24 

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/137422487/9de263c2-c76c-411e-8c64-d452ace85de3)

**Comment by Mihai-Ac** [comment]
Hello @willrod369 
Thanks for reporting this.

Issue has been addressed in https://github.com/MicrosoftLearning/mslearn-fabric/pull/45
