### ISSUE TITLE
Organize Fabric Lakehouse - Lab - Step 8 Error

### ISSUE THREAD

**Issue by willrod369** [MicrosoftLearning/mslearn-fabric#43]
# Module: Organize a Fabric lakehouse using medallion architecture design
#### Step: 8

Description of issue: display output is referencing old data frame (i.e., step 5), not data frame we procured in this step. This does not effect usability (i.e., code is not 'broken' in that it gives an error. 

Repro steps:

1. Load Lab
2. Work until Step 5
3. Note that the output is not the dfdimCustomer_silver dataframe we just built

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/137422487/b6c70282-5a9d-41d4-b7f0-91fa80c30438)

**Comment by Mihai-Ac** [comment]
Hello @willrod369 

We have addressed the issue in https://github.com/MicrosoftLearning/mslearn-fabric/pull/45
