### ISSUE TITLE
Lab 03b - "Free user cannot apply model changes" error when trying to add relationships

### ISSUE THREAD

**Issue by MarkFromTheInternet** [MicrosoftLearning/mslearn-fabric#60]
# Module: Create a medallion architecture in a Microsoft Fabric lakehouse
#### Step: 03

Description of issue
When trying to add the table relationships, I get an error:
Free User cannot apply model changes, upgrade to PowerBI Pro.

I verified the "data model settings" change in the earlier portion of the lab was applied.

https://learn.microsoft.com/en-us/fabric/get-started/fabric-trial#users-who-are-new-to-power-bi
I set this up on a new account, with no Power BI license, associated with an account I created in my existing Azure subscription. I followed these steps to enable my Fabric trial...so I would expect to have a Power BI Free license.

https://learn.microsoft.com/en-us/power-bi/consumer/end-user-features#feature-list
This table shows that I should be able to edit datasets in my workspace with a Free license.

It's not clear if the Power BI license & the Fabric license are separate, or if a (Fabric) Trial license should have the same functionality as a (Power BI) Free license.

If this is a service-side bug & not the expected behavior in Fabric, please let me know and I'll report it via their support channel.

Repro steps:

1. Follow steps in this section: https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/03b-medallion-lakehouse.html#create-a-dataset
2. Hit error when trying to add any relationship between dimension & fact tables

**Comment by shannonlindsay** [comment]
Hi Mark - this is a product issue. We have alerted the product team. Thanks for raising it here!
