### ISSUE TITLE
Lab 12 - All steps in 'SELECT' example have the same number

### ISSUE THREAD

**Issue by MarkFromTheInternet** [MicrosoftLearning/mslearn-fabric#72]
# Module: Query data from a Kusto Query database in Microsoft Fabric
### Task: SELECT data from our sample dataset using KQL

Description of issue
https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/12-query-data-in-kql-database.html

The markdown version of the page looks correct, but the HTML version of this page shows "1." for all of the numbered steps in this section and the ones below it.

I made changes in [this private branch](https://github.com/MarkFromTheInternet/mslearn-fabric/blob/MM-lab12-suggestion/Instructions/Labs/12-query-data-in-kql-database.md) to make the formatting more consistent with other labs:

line break
4 spaces - start code block
3 spaces before each line of code
4 spaces - end code block 
line break

But there were still some blocks, like 'order by' and 'where' that only had 1 step. But they didn't display correctly until a number was added to the text block. Investigated, but it's not clear to me why this would be required. That's why I didn't submit a PR for it.

**Comment by TheJamesHerring** [comment]
@MarkFromTheInternet thanks for the catch. Fixed tabbing
