### ISSUE TITLE
Create a Lakehouse — There is no Synapse Data Engineering

### ISSUE THREAD

**Issue by mrgnw** [MicrosoftLearning/mslearn-fabric#73]
# Module: [01 Create a Lakehouse](https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/01-lakehouse.html)
#### Step: 01

Description of issue

> On the Microsoft Fabric home page, select Synapse Data Engineering.

There is no Synapse Data Engineering on the Microsoft Fabric home page.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/2504532/72802671-767f-466f-b33f-523ae3fc772f)

Repro steps:

1. [Activate a Microsoft Fabric trial](https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/01-lakehouse.html#activate-a-microsoft-fabric-trial)
1. [Create a workspace](https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/01-lakehouse.html#create-a-workspace)
    1. verify that workspace is a Fabric workspace
        1. The workspace title is followed by a 💎 ("Fabric Content" appears when putting mouse over the diamond)
        1. The license in workspace settings is a Fabric license (`...` ▸ `Workspace settings` ▸ `Premium`)
           - attempted two license types, unable to access with either:
               - license is "Trial"
               - license is a "Fabric capacity" with a Fabric capacity created in Azure
    1. Zone: Central US (Iowa)
        1. Central US doesn't appear to be listed but North Central and South Central are  https://learn.microsoft.com/en-us/fabric/admin/region-availability

**Comment by mrgnw** [comment]
- [ ] Fabric trial: I did not find a way to change the zone
- [x] Azure Fabric capacity: solved by creating a capacity in a [supported zone](https://learn.microsoft.com/en-us/fabric/admin/region-availability)
    - Deleted my existing fabric capacity
    - created a new one with a zone from [region availability](https://learn.microsoft.com/en-us/fabric/admin/region-availability)
    - I can now access the [Data Engineering](https://app.fabric.microsoft.com/home?experience=data-engineering) experience via the persona switcher
        - "Synapse Data Engineering" is still not visible on the page, but clicking "Power BI" opens the persona switcher and includes a Synapse with: Data Engineering, Data Science, Data Warehouse, Real-time data analytics

**Comment by MarkFromTheInternet** [comment]
Hi,

The page in your screenshot looks like it's from the Power BI persona, not the main Fabric homepage https://app.fabric.microsoft.com/home

As far as the workspace + licensing, note that this is different on a per-workspace basis. Like you, I created a Fabric Trial. When I select "My workspace" -> workplace settings -> Premium, the options I can select are Pro and Trial (Pro is selected). When I select any other workspace that I've created, the options are Pro, Premium per-user and Trial (Trial is selected). Not sure why they're different, just an FYI.

As far as the persona picker not being in the bottom left corner when in that experience, that seems like a service issue and not a content issue as it displays correctly for me. Maybe something specific to your region, or browser? My capacity is in East US 2 (Virginia), I'm using Microsoft Edge.

**Comment by mrgnw** [comment]
The core issue seems to be related to region, so the primary resolution would be to prevent Fabric Trial signups in unsupported regions.

Until this issue with the fabric trial signup is resolved, I would also recommend updating the docs with a note that the Fabric trial needs to be created in a [supported region](https://learn.microsoft.com/en-us/fabric/admin/region-availability) for any data engineering options to appear.

**Comment by shannonlindsay** [comment]
@mrgnw - this is a product bug that the team is aware of (in Central US). Thanks for the suggestion to update the text, we'll take that on board.

**Comment by GraemeMalcolm** [comment]
Closing as this is an issue with the service (and has been reported to the team), not the content
