### ISSUE TITLE
Lab 08c - Copying from GitHub pages adds space

### ISSUE THREAD

**Issue by cmaneu** [MicrosoftLearning/mslearn-fabric#74]
# Module: 00
#### Step: All

Description of issue
When you're copying code from the [GitHub Pages site](https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/08c-data-science-train.html) into Fabric notebook editor, it adds a space at the beginning of each line. The Python code syntax is not correct anymore.

The issue does not happen if we copy code from GitHub repository. 

Repro seps:

1. Go to [GitHub Pages site](https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/08c-data-science-train.html)
1. Copy any code block
1. Open a new notebook in Fabric 
1. Paste the content on a code cell

**Comment by madiepev** [comment]
Thanks for reporting this. Issue should be fixed now!
