### ISSUE TITLE
LP03: Lakehouse creation fails with trial capacity located in Central US

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/mslearn-fabric#75]
- Learning Path 03: Use delta tables in Apache Spark
- Task: Create a lakehouse and upload data
- step 1

https://github.com/MicrosoftLearning/mslearn-fabric/blob/7513f155c43635665f488ce6353146490d9f744b/Instructions/Labs/03-delta-lake.md#create-a-lakehouse-and-upload-data

When the trial capacity provisioned in previous steps is located in the Central US region, a lakehouse cannot be created at the above-referenced step. The message quoted below is displayed.

> Upgrade to a paid Microsoft Fabric capacity
> To work with Lakehouse, this workspace needs to use a Fabric enhanced
> capacity. You can purchase a fabric capacity on the Azure portal using your
> Azure subscription. Learn more.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/134323425/d3270f49-0e75-41df-8ef1-0da77518ad37)
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/134323425/4dc221b7-6e66-41e4-80a2-d9b5483e9dd9)

Creating the lakehouse with a trial capacity in the North Central US region succeeds.

Per the below Microsoft doc, the Central US region is not a supported Fabric region.

https://learn.microsoft.com/en-us/fabric/admin/region-availability

The below document suggests that the "home region" viewable through the "About Microsoft Fabric" dialog should determine the location of the trial capacity. However, we observed that despite this home region being set to North Central US, trials still sometimes provision in Central US.

https://learn.microsoft.com/en-us/fabric/get-started/fabric-trial#considerations-and-limitations

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/134323425/b093735c-2563-4614-8532-7b3dc9699d7c)
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/134323425/f91fcb74-5689-4d6c-a077-4d0efac2bc4b)

Per this comment in another issue, there is a known Fabric issue relating to the Central US region. We are unaware of the details of this issue, but it may be relevant here.

https://github.com/MicrosoftLearning/mslearn-fabric/issues/73#issuecomment-1800274492

Central US trial assignment appears to be somewhat random. We do not know of a method to explicitly set the location of a trial to be used with this lab. Avoiding Central US should prevent the issue, if a means of doing so exists.

Repro steps:

1. Complete tasks previous to "Create a lakehouse and upload data".
1. On the Fabric home page, navigate to Settings -> Admin portal -> Capacity settings -> Trial.
1. Check the region listed for the active trial capacity. If it is set to the Central US location, continue with "Create a lakehouse and upload data" to observe lakehouse creation failure. If set to another location, restart the lab with a fresh environment and repeat repro steps as needed until a Central US location is assigned.

**Comment by tylerfarmer1** [comment]
I've tried 10 different labs with our hoster, and every time you try to create a Lakehouse it says that we need upgrade to a paid subscription.  Every time you try to create a new Workspace, the instructions say to create one that includes "Fabric Capacity" but it is always grayed-out (disabled).   So, the course can't even be run at this point.

**Comment by shannonlindsay** [comment]
@SkillableMG - Fabric trials do not work in the Central US region. This is a bug that is known by the Fabric product team. I'm going to discuss this with my team to understand what the best course of action is - will leave the issue open until we have a solution. Thanks for bringing this to our attention.

**Comment by GraemeMalcolm** [comment]
This should now be resolved for the hosted lab environment provided to training partners. The issue with some regions failing is a bug in the service (which the team are aware of), not a content bug - so closing here.
