### ISSUE TITLE
Lab 16 image pathing in invalid

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/mslearn-fabric#79]
#### Step: 00

Description of issue
- invalid imaging 
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/151560619/b545bd7c-7182-422e-b88d-e752434c00c9)
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/151560619/2fd8b85e-b884-4796-8b8b-ab48e4f3efca)

Repro steps:

1. change pathing for image

**Comment by shannonlindsay** [comment]
Noted - will fix.
