### ISSUE TITLE
Lab 17 Image pathing invalid

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/mslearn-fabric#80]
#### Step: 00

Description of issue
- pathing issue
invalid:
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/151560619/388f3b6b-9dc1-442f-9934-d2de56af4947)

valid:
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/151560619/c82aad55-16af-42ce-8d85-8b88c5b3afbb)

Repro steps:

1. edit pathing of image

**Comment by shannonlindsay** [comment]
Noted - will fix.

**Comment by Mihai-Ac** [comment]
Addressed in #85
