### ISSUE TITLE
SQL Server Primary Key Constraint Syntax Error and Invalid Object Name in MS Fabric Tutorial

### ISSUE THREAD

**Issue by ibanaham** [MicrosoftLearning/mslearn-fabric#90]
# Module: 00
#### Step: 00

I encountered a syntax error in the T-SQL script provided in the Microsoft Fabric tutorial for data warehousing in SQL Datawarehouse. The error pertains to the use of `NOT ENFORCED` in the primary key constraint syntax which is not recognized by SQL Server.

Additionally, the script references an object `[ExternalData].[dbo].[staging_sales]` which does not exist, leading to an 'Invalid object name' error.

Repro steps:

1. Execute the provided T-SQL script to create schemas, tables, and a view.
2. Encounter syntax error on `NOT ENFORCED` clause when adding a primary key constraint.
3. Encounter 'Invalid object name' error when creating the view `[Sales].[Staging_Sales]`.

The errors were resolved by:
- Removing the `NOT ENFORCED` clause from the primary key constraint definition as it is not a valid syntax in SQL Server.
- Correcting the object name to match the actual Lakehouse name used in the exercise instead of `[ExternalData]`.

Here is the link to the exercise where I encountered the issue:
[MS Fabric Tutorial Exercise](https://microsoftlearning.github.io/mslearn-fabric/Instructions/Labs/06a-data-warehouse-load.html)

Please update the tutorial to correct the syntax and ensure the object names are clearly explained to match the user's environment setup.

**Comment by Mihai-Ac** [comment]
Hello @ibanaham 
Thanks for reporting.
Issues fixed with latest update.
