### ISSUE TITLE
Lab 06a invalid column name in query

### ISSUE THREAD

**Issue by Solita-VillePuuska** [MicrosoftLearning/mslearn-fabric#91]
# Module: Load data into a Microsoft Fabric data warehouse
#### Step: 1

https://github.com/MicrosoftLearning/mslearn-fabric/blob/main/Instructions/Labs/06a-data-warehouse-load.md#run-analytical-queries

Description of issue

In the query 
```
SELECT c.CustomerName, SUM(s.UnitPrice * s.Quantity) AS TotalSales
FROM Sales.Fact_Sales s
JOIN Sales.Dim_Customer c
ON s.SalesOrderNumber = c.SalesOrderNumber
WHERE YEAR(s.OrderDate) = 2021
GROUP BY c.CustomerName
ORDER BY TotalSales DESC;
```
the column to join tables on should be CustomerID; Dim_Customer does not have the column SalesOrderNumber.

Repro steps:

1. Follow the lab instructions.

**Comment by Mihai-Ac** [comment]
Hello @Solita-VillePuuska 

An update has been made and this issue has been fixed.

Regards,
Mihai
